### ISSUE TITLE
We need a better dictionary

### ISSUE THREAD

**Issue by bodonovan** [bodonovan/wordle_cheat#3]
The plain text 'words' file needs updating

**Comment by mpa-LHutchinson** [comment]
Hi @bodonovan, can you assign this issue to me and give it the "hacktoberfest" label? I'll get working on it as soon as I can today. Also, is there anything about the file specifically that you want changed?

**Comment by bodonovan** [comment]
I don't think I explained what is involved so here goes:

- The words file is supposed to contain. all English words
- Only 4 and 5 letter words matter (all other words get ignored)
- - 5 letter words might be the wordle hidden word
- - 4 letter words might get s added to the end to become a wordle answer
- Right now the list is a file which I _stole_ from my Mac. I use wordle_cheat to solve the wordle puzzle and I occasionally notice that the hidden word is not in my dictionary. I am not sure where to get a better dictionary, but I just know there must be one out there

Is that clear?

**Comment by mpa-LHutchinson** [comment]
So the current file doesn't contain every 4-5 letter word, and you need these missing words to be added?

**Comment by bodonovan** [comment]
> So the current file doesn't contain every 4-5 letter word, and you need these missing words to be added?

exactly

**Comment by bodonovan** [comment]
FYI. If you have a Mac or Linux system you will find the current dictionary at /usr/share/dict/words

**Comment by bodonovan** [comment]
I am not sure where to get a list of words, but [a Google search](https://www.google.com/search?q=list+of+english+words) would probably be a good place to start looking.

By the way, I googled hacktober-fest and it looks like a cool event.

**Comment by mpa-LHutchinson** [comment]
@bodonovan I updated this issue with #4

**Comment by mpa-LHutchinson** [comment]
@bodonovan can you add the "hacktoberfest" topic to the entire repo so my pull request can get accepted for hacktoberfest? Sorry for not clarifying this earlier.

**Comment by bodonovan** [comment]
I am not sure how to add the _hacktoberfest-accepted_ tag to the entire repository so I added to this issue instead.

Thanks again for your help

**Comment by mpa-LHutchinson** [comment]
My apologies, I meant to say topic, not tag. You can add topics to a repo and if you can add "hacktoberfest" as a topic in your repo it should go through. You can also try adding the "hacktoberfest-accepted" tag to the pull request associated with this issue (#4). Sorry for the confusion.
